export let products = [
	{
		id: 1,
		nombre: 'Café',
		referencia: 'C001',
		precio: 5000,
		peso: 250,
		categoria: 'Bebidas',
		stock: 100,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 2,
		nombre: 'Galleta',
		referencia: 'G002',
		precio: 2000,
		peso: 150,
		categoria: 'Snacks',
		stock: 50,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 3,
		nombre: 'Té',
		referencia: 'T001',
		precio: 3000,
		peso: 200,
		categoria: 'Bebidas',
		stock: 150,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 4,
		nombre: 'Jugo de naranja',
		referencia: 'J001',
		precio: 4000,
		peso: 300,
		categoria: 'Bebidas',
		stock: 80,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 5,
		nombre: 'Sándwich de pollo',
		referencia: 'S001',
		precio: 8000,
		peso: 350,
		categoria: 'Comidas',
		stock: 60,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 6,
		nombre: 'Muffin de chocolate',
		referencia: 'M001',
		precio: 2500,
		peso: 180,
		categoria: 'Snacks',
		stock: 120,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 7,
		nombre: 'Croissant',
		referencia: 'C001',
		precio: 3500,
		peso: 200,
		categoria: 'Bollería',
		stock: 100,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 8,
		nombre: 'Ensalada César',
		referencia: 'E001',
		precio: 12000,
		peso: 400,
		categoria: 'Comidas',
		stock: 40,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 9,
		nombre: 'Agua mineral',
		referencia: 'A001',
		precio: 1500,
		peso: 500,
		categoria: 'Bebidas',
		stock: 200,
		fechaCreacion: new Date().toISOString(),
	},
	{
		id: 10,
		nombre: 'Batido de fresa',
		referencia: 'B001',
		precio: 3500,
		peso: 250,
		categoria: 'Bebidas',
		stock: 90,
		fechaCreacion: new Date().toISOString(),
	},
];
